name: docs

on: workflow_call

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install -e .
      - run: pip install pdoc
      # ADJUST THIS: build your documentation into docs/.
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: pdoc src/sciterra -d google --math -o ./docs

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/
